CREATE TABLE CLIENTE(
DNI CHAR(8) PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO VARCHAR2(50) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
TELEFONO NUMBER(10)
);
INSERT INTO cliente VALUES(1,'Andres','Leon','dandresleon64@gmail.com',3124448879);
update cliente set TELEFONO = 312555 where DNI = 1;
SELECT * FROM CLIENTE;

CREATE OR REPLACE PROCEDURE SP_INSERT_CLIENTE(
P_DNI IN cliente.dni%TYPE,
P_NOMBRE IN cliente.nombre%TYPE,
P_APELLIDO IN cliente.apellido%TYPE,
P_EMAIL IN cliente.email%TYPE,
P_TELEFONO IN cliente.telefono%TYPE,
P_RESULT OUT VARCHAR2

)
AS 
BEGIN
  INSERT INTO cliente VALUES(P_DNI,P_NOMBRE,P_APELLIDO,P_EMAIL,P_TELEFONO);
  p_result:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
   WHEN OTHERS THEN
    p_result:= 'ERROR AL ACTUALIZAR';  
  ROLLBACK;
END;



CREATE OR REPLACE PROCEDURE SP_UPDATE_CLIENTE(
P_DNI IN cliente.dni%TYPE,
P_NOMBRE IN cliente.nombre%TYPE,
P_APELLIDO IN cliente.apellido%TYPE,
P_EMAIL IN cliente.email%TYPE,
P_TELEFONO IN cliente.telefono%TYPE,
P_RESULT OUT VARCHAR2

)
AS 
BEGIN

  UPDATE cliente 
  SET   NOMBRE = P_NOMBRE, APELLIDO = P_APELLIDO,EMAIL = P_EMAIL,TELEFONO = P_TELEFONO
  WHERE DNI = p_dni;
    p_result:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
   EXCEPTION
    WHEN OTHERS THEN
    p_result:= 'ERROR AL ACTUALIZAR';  
  ROLLBACK;
END;



CREATE OR REPLACE PROCEDURE SP_DELETE_CLIENTE(
P_DNI IN cliente.dni%TYPE,
P_RESULT OUT VARCHAR2
)
AS 
BEGIN

  DELETE cliente WHERE dni = p_dni;
    p_result:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
   EXCEPTION
    WHEN OTHERS THEN
    p_result:= 'ERROR AL ELIMINAR';  
  ROLLBACK;
END;



CREATE OR REPLACE PROCEDURE SP_SELECT_CLIENTE(
  P_CURSOR OUT SYS_REFCURSOR  
)
AS 
BEGIN
 OPEN P_CURSOR FOR
 SELECT DNI,NOMBRE,APELLIDO,EMAIL,TELEFONO
 FROM cliente;

 END;

 
 
 execute  sp_select_cliente;



